### ISSUE TITLE
Can I get the "meta"?

### ISSUE THREAD

**Issue by ericntd** [faogustavo/JSONApi#13]
The `JSONApiObject` class does not include a `meta` field so I suppose I can't?
I'm happy to have it as a JSON object/ string. I don't need your library to de-serialise it, I can do that myself.

**Comment by mikepschneider** [comment]
created a pull request for this: https://github.com/faogustavo/JSONApi/pull/26

**Comment by faogustavo** [comment]
Sorry for the late response. This was merged and is on the new version.
