### ISSUE TITLE
Multiple nesting level isue

### ISSUE THREAD

**Issue by Rivaz93** [faogustavo/JSONApi#14]
For my JSON:API response, I am not able to deserialize it.
`{
    "data": [{
        "id": "1",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-07T08:00:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "1",
                    "type": "conditions"
                }, {
                    "id": "2",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "3",
                    "type": "images"
                }, {
                    "id": "2",
                    "type": "images"
                }, {
                    "id": "1",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "2",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T16:56:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "3",
                    "type": "conditions"
                }, {
                    "id": "4",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "6",
                    "type": "images"
                }, {
                    "id": "5",
                    "type": "images"
                }, {
                    "id": "4",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "3",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T13:58:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "5",
                    "type": "conditions"
                }, {
                    "id": "6",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "9",
                    "type": "images"
                }, {
                    "id": "8",
                    "type": "images"
                }, {
                    "id": "7",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "4",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T16:58:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "7",
                    "type": "conditions"
                }, {
                    "id": "8",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "12",
                    "type": "images"
                }, {
                    "id": "11",
                    "type": "images"
                }, {
                    "id": "10",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "5",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T14:58:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "9",
                    "type": "conditions"
                }, {
                    "id": "10",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "15",
                    "type": "images"
                }, {
                    "id": "14",
                    "type": "images"
                }, {
                    "id": "13",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "6",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T14:58:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "11",
                    "type": "conditions"
                }, {
                    "id": "12",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "18",
                    "type": "images"
                }, {
                    "id": "17",
                    "type": "images"
                }, {
                    "id": "16",
                    "type": "images"
                }]
            }
        }
    }, {
        "id": "7",
        "type": "vouchers",
        "attributes": {
            "name": "Nume voucher",
            "description": "Prima descriere",
            "price": "21.0",
            "quantity": 100,
            "start_date": "2016-08-04T14:08:00.000Z",
            "end_date": "2016-08-08T16:00:00.000Z",
            "category_id": 2,
            "limit_per_user": 5,
            "state": "approved",
            "supplier_id": 47
        },
        "relationships": {
            "conditions": {
                "data": [{
                    "id": "13",
                    "type": "conditions"
                }, {
                    "id": "14",
                    "type": "conditions"
                }]
            },
            "images": {
                "data": [{
                    "id": "21",
                    "type": "images"
                }, {
                    "id": "20",
                    "type": "images"
                }, {
                    "id": "19",
                    "type": "images"
                }]
            }
        }
    }],
    "included": [{
        "id": "1",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "1",
                    "type": "rules"
                }, {
                    "id": "2",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "1",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "2",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "2",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "3",
                    "type": "rules"
                }, {
                    "id": "4",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "3",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "4",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "3",
        "type": "images",
        "attributes": {
            "imageable_id": 1,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/1/3/file.jpeg"
                }
            }
        }
    }, {
        "id": "2",
        "type": "images",
        "attributes": {
            "imageable_id": 1,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/1/2/file.jpeg"
                }
            }
        }
    }, {
        "id": "1",
        "type": "images",
        "attributes": {
            "imageable_id": 1,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/1/1/file.jpeg"
                }
            }
        }
    }, {
        "id": "3",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "5",
                    "type": "rules"
                }, {
                    "id": "6",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "5",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "6",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "4",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "7",
                    "type": "rules"
                }, {
                    "id": "8",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "7",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "8",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "6",
        "type": "images",
        "attributes": {
            "imageable_id": 2,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/2/6/file.jpeg"
                }
            }
        }
    }, {
        "id": "5",
        "type": "images",
        "attributes": {
            "imageable_id": 2,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/2/5/file.jpeg"
                }
            }
        }
    }, {
        "id": "4",
        "type": "images",
        "attributes": {
            "imageable_id": 2,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/2/4/file.jpeg"
                }
            }
        }
    }, {
        "id": "5",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "9",
                    "type": "rules"
                }, {
                    "id": "10",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "9",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "10",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "6",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "11",
                    "type": "rules"
                }, {
                    "id": "12",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "11",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "12",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "9",
        "type": "images",
        "attributes": {
            "imageable_id": 3,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/3/9/file.jpeg"
                }
            }
        }
    }, {
        "id": "8",
        "type": "images",
        "attributes": {
            "imageable_id": 3,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/3/8/file.jpeg"
                }
            }
        }
    }, {
        "id": "7",
        "type": "images",
        "attributes": {
            "imageable_id": 3,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/3/7/file.jpeg"
                }
            }
        }
    }, {
        "id": "7",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "13",
                    "type": "rules"
                }, {
                    "id": "14",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "13",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "14",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "8",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "15",
                    "type": "rules"
                }, {
                    "id": "16",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "15",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "16",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "12",
        "type": "images",
        "attributes": {
            "imageable_id": 4,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/4/12/file.jpeg"
                }
            }
        }
    }, {
        "id": "11",
        "type": "images",
        "attributes": {
            "imageable_id": 4,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/4/11/file.jpeg"
                }
            }
        }
    }, {
        "id": "10",
        "type": "images",
        "attributes": {
            "imageable_id": 4,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/4/10/file.jpeg"
                }
            }
        }
    }, {
        "id": "9",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "17",
                    "type": "rules"
                }, {
                    "id": "18",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "17",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "18",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "10",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "19",
                    "type": "rules"
                }, {
                    "id": "20",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "19",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "20",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "15",
        "type": "images",
        "attributes": {
            "imageable_id": 5,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/5/15/file.jpeg"
                }
            }
        }
    }, {
        "id": "14",
        "type": "images",
        "attributes": {
            "imageable_id": 5,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/5/14/file.jpeg"
                }
            }
        }
    }, {
        "id": "13",
        "type": "images",
        "attributes": {
            "imageable_id": 5,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/5/13/file.jpeg"
                }
            }
        }
    }, {
        "id": "11",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "21",
                    "type": "rules"
                }, {
                    "id": "22",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "21",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "22",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "12",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "23",
                    "type": "rules"
                }, {
                    "id": "24",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "23",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "24",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "18",
        "type": "images",
        "attributes": {
            "imageable_id": 6,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/6/18/file.jpeg"
                }
            }
        }
    }, {
        "id": "17",
        "type": "images",
        "attributes": {
            "imageable_id": 6,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/6/17/file.jpeg"
                }
            }
        }
    }, {
        "id": "16",
        "type": "images",
        "attributes": {
            "imageable_id": 6,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/6/16/file.jpeg"
                }
            }
        }
    }, {
        "id": "13",
        "type": "conditions",
        "attributes": {
            "condition_type": 1,
            "end_date": "2016-08-08T19:13:00.000Z",
            "start_date": "2016-08-07T18:00:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "25",
                    "type": "rules"
                }, {
                    "id": "26",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "25",
        "type": "rules",
        "attributes": {
            "threshold": 100,
            "sale_percentage": 20
        }
    }, {
        "id": "26",
        "type": "rules",
        "attributes": {
            "threshold": 200,
            "sale_percentage": 40
        }
    }, {
        "id": "14",
        "type": "conditions",
        "attributes": {
            "condition_type": 2,
            "end_date": "2016-08-10T19:13:00.000Z",
            "start_date": "2016-08-08T19:13:00.000Z"
        },
        "relationships": {
            "rules": {
                "data": [{
                    "id": "27",
                    "type": "rules"
                }, {
                    "id": "28",
                    "type": "rules"
                }]
            }
        }
    }, {
        "id": "27",
        "type": "rules",
        "attributes": {
            "threshold": 300,
            "sale_percentage": 50
        }
    }, {
        "id": "28",
        "type": "rules",
        "attributes": {
            "threshold": 500,
            "sale_percentage": 70
        }
    }, {
        "id": "21",
        "type": "images",
        "attributes": {
            "imageable_id": 7,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/7/21/file.jpeg"
                }
            }
        }
    }, {
        "id": "20",
        "type": "images",
        "attributes": {
            "imageable_id": 7,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/7/20/file.jpeg"
                }
            }
        }
    }, {
        "id": "19",
        "type": "images",
        "attributes": {
            "imageable_id": 7,
            "imageable_type": "Voucher",
            "image": {
                "image": {
                    "url": "/uploads/images/voucher/7/19/file.jpeg"
                }
            }
        }
    }]
}`

My classes:

`@Type("vouchers")
public class Voucher extends Resource implements Serializable {
    private String name;
    private String description;
    private double price;
    private int quantity;
    private String state;
    @SerialName("start_date")
    private String startDate;
    @SerialName("end_date")
    private String endDate;
    @SerialName("category_id")
    private int category;
    @SerialName("limit_per_user")
    private int limit;
    @SerialName("supplier_id")
    private int suplierId;
    private JSONList<Condition> conditions;
    private JSONList<Images> images;

```
public String getName() {
    return name;
}

public void setName(String name) {
    this.name = name;
}

public String getDescription() {
    return description;
}

public void setDescription(String description) {
    this.description = description;
}

public double getPrice() {
    return price;
}

public void setPrice(long price) {
    this.price = price;
}

public int getQuantity() {
    return quantity;
}

public void setQuantity(int quantity) {
    this.quantity = quantity;
}

public String getStartDate() {
    return startDate;
}

public void setStartDate(String startDate) {
    this.startDate = startDate;
}

public String getEndDate() {
    return endDate;
}

public void setEndDate(String endDate) {
    this.endDate = endDate;
}

public int getCategory() {
    return category;
}

public void setCategory(int category) {
    this.category = category;
}

public int getLimit() {
    return limit;
}

public void setLimit(int limit) {
    this.limit = limit;
}

public String getState() {
    return state;
}

public void setState(String state) {
    this.state = state;
}

public JSONList<Condition> getConditions() {
    return conditions;
}

public void setConditions(JSONList<Condition> conditions) {
    this.conditions = conditions;
}

public JSONList<Images> getImages() {
    return images;
}

public void setImages(JSONList<Images> images) {
    this.images = images;
}

public void setPrice(double price) {
    this.price = price;
}

public int getSuplierId() {
    return suplierId;
}

public void setSuplierId(int suplierId) {
    this.suplierId = suplierId;
}
```

}`

`@Type("rules")
public class Rule extends Resource{
    private int threshold;
    @SerialName("sale_percentage")
    private int salePercent;

```
public int getThreshold() {
    return threshold;
}

public void setThreshold(int threshold) {
    this.threshold = threshold;
}

public long getSalePercent() {
    return salePercent;
}

public void setSalePercent(int salePercent) {
    this.salePercent = salePercent;
}
```

}
`

`@Type("images")
public class Images extends Resource{
    @SerialName("imageable_id")
    private int imageableId;
    @SerialName("imageable_type")
    private String imageableType;
    private Map<String, Image> image;

```
public long getImageableId() {
    return imageableId;
}

public void setImageableId(int imageableId) {
    this.imageableId = imageableId;
}

public String getImageableType() {
    return imageableType;
}

public void setImageableType(String imageableType) {
    this.imageableType = imageableType;
}

public Map<String, Image> getImage() {
    return image;
}

public void setImage(Map<String, Image> image) {
    this.image = image;
}
```

}
`

`@Type("image")
public class Image extends Resource {

```
private String url;

public String getUrl() {
    return url;
}

public void setUrl(String url) {
    this.url = url;
}

@Override
public String toString() {
    return "{" + "\"url\":" + url + "}";
}
```

}
`

`@Type("conditions")
public class Condition extends Resource{
    @SerialName("condition_type")
    private int conditionType;
    @SerialName("end_date")
    private String endDate;
    @SerialName("start_date")
    private String startDate;
    @Expose
    private JSONList<Rule> rules;

```
public long getConditionType() {
    return conditionType;
}

public void setConditionType(int conditionType) {
    this.conditionType = conditionType;
}

public String getEndDate() {
    return endDate;
}

public void setEndDate(String endDate) {
    this.endDate = endDate;
}

public String getStartDate() {
    return startDate;
}

public void setStartDate(String startDate) {
    this.startDate = startDate;
}

public JSONList<Rule> getRules() {
    return rules;
}

public void setRules(JSONList<Rule> rules) {
    this.rules = rules;
}
```

}
`

**Comment by ericn37** [comment]
Multi-level nesting does not conform JSONAPI specs which this library support.
You have to deal with the 3rd level and beyond separately.

I initially wanted something like what you want here as well. However, I've come to realise that it makes sense not to nest too much. It's good design to only nest 1 level - 2 levels in total

**Comment by starikovskii** [comment]
Can u provide link to  JSONAPI multi-level specs please?

**Comment by faogustavo** [comment]
Sorry for the late response, but did you find what caused the problem?

**Comment by faogustavo** [comment]
I think this task is duplicated with #12 . I'll close it here and keep track on that.
