### ISSUE TITLE
Relationships objects are not parsed correctly if a field is null

### ISSUE THREAD

**Issue by MichaelSiddi** [faogustavo/JSONApi#17]
Hi, we are facing an issue when parsing the relationships of an object. 

If you have an object like

```
{
    "type": "articles",
    "id": "1",
    "attributes": {
        "title": "Rails is Omakase"
    },
    "relationships": {
        "author": {
            "links": {
                "related": "http://example.com/articles/1/author"
            },
            "data": null
        }
    }
}
```

where data is _null_, it seems the links are not parsed, the related url is null. If I force the server to return an empty array ( `"data" : []` ) as value of the "data" field, the links are parsed correctly. 

As 1.0 JSONAPI specification the data field can be null:

> Resource linkage MUST be represented as one of the following:
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.
> - a single resource identifier object for non-empty to-one relationships.
> - an array of resource identifier objects for non-empty to-many relationships.

Is it possible to have a check? thank you very much

**Comment by mikedvc** [comment]
A workround for the problem: #18 
Do you think could be a 'clean' fix?

Thanks
