### ISSUE TITLE
has no zero argument constructor

### ISSUE THREAD

**Issue by leijdekkers** [faogustavo/JSONApi#23]
I am getting this error "has no zero argument constructor" even if my class has an empty constructor. Any idea what is wrong here?

OK fixed it! In my Gradle i had " minifyEnabled true" for both debug and release and as a consequence it removed the empty constructors. 

So if you set "minifyEnabled true" you MUST also activate "useProguard true" and in your proguard description you must set this:
-keep public class * extends com.gustavofao.jsonapi.Models.Resource

**Comment by faogustavo** [comment]
Thanks for the tip. I'll add it to the readme.
