### ISSUE TITLE
Post with Retrofit2

### ISSUE THREAD

**Issue by Barrak90** [faogustavo/JSONApi#24]
First of All I would like to thank you for this.

I have an issue with posting Json body, where the response is JsonApiObject, it sends the request with empty body.
Body of post request:
`{
    "email": "demo@test.it",
    "password": "12345678"
}`
Here is my code:

Retrofit:
`Retrofit instance = new Retrofit.Builder()
                    .baseUrl(BuildConfig.BASE_URL)
                    .addConverterFactory(getConverter()) //it has all the models in response
                    .client(myHttpLoger().build())
                    .build();`

  Call interface:
`public interface SignInApi{  
        @POST("/sign_in")
        Call<JSONApiObject> getSignIn( @Body SignIn signIn);
    }`
SignIn request class:
`public static class SignIn extends Resource{
        String email,
        password,
        public SignIn(String email, String password) {
            this.email = email;
            this.password = password;
        }
    }`

Call:
`
        SignIn signInRequest = new SignIn(userEmail, userPassword);
        Call<JSONApiObject> call = instance.create(SignInApi.class).getSignIn(signInRequest);
        call.enqueue(new Callback<JSONApiObject>() {
            @Override
            public void onResponse(Call<JSONApiObject> call, Response<JSONApiObject> response) {          
            }
            @Override
            public void onFailure(Call<JSONApiObject> call, Throwable t) {
            }
        });`

In the logs I see empty body, and when I use JsonObject instead of SignIn object I get Class Cast Exception 

> com.google.gson.JsonObject cannot be cast to java.util.List

Thank you in advance

**Comment by mikepschneider** [comment]
I'm having a similar problem.  When I pass a resource object into a post request, I was expecting it would turn into JSON Api format.  However it does this: 
Form Params:
user: 	com.company.data.User@750cc5c

An example of how to use POST requests in combo with Retrofit2 would be great.

**Comment by testica** [comment]
Same problem here..

**Comment by testica** [comment]
try to keep empty the constructor and add getters and setters
```java
public static class SignIn extends Resource{
 String email, password; 
 public SignIn() { }
 //.... gettters and setters
}
```

**Comment by faogustavo** [comment]
Sorry for the late response, but did you find what caused the problem or solved your problem?

**Comment by DrCod** [comment]
Facing a similar problem here. Please how do you resolve this?

**Comment by testica** [comment]
@DrCod Did you try my comment above ?

**Comment by DrCod** [comment]
@testica  kindly have a look at my sample code...

//User Model
@Type("users")
public class User extends Resource {

    private  String email;
    private String password;
   ....
//my empty constructor
    public User(){}

    public void setEmail(String email) {
        this.email = email;
    }
  public String getEmail() {
        return email;
    }
...
...

public interface ApiInterface {
    @POST("/users")
    Call<JSONApiObject>register(@Body User user);
//my retrofit object
 Retrofit retrofit = new Retrofit.Builder()
                .addConverterFactory(JSONConverterFactory.create(User.class))
                .baseUrl(REGISTER_URI)
                .build();

        Call<JSONApiObject> obj =retrofit.create(ApiInterface.class).register(user);
        obj.enqueue(new Callback<JSONApiObject>() {
            @Override
            public void onResponse(Call<JSONApiObject> call, Response<JSONApiObject> response) {

                if (response.isSuccessful()){
                    signUpView.signupSuccess();
                }
                else {
                    signUpView.signupFailed();
                }
            }
            @Override
            public void onFailure(Call<JSONApiObject> call, Throwable t) {
                call.cancel();
            }
        });


But iIt keeps giving me  the signUpView.signupFailed() view. Is there something i am missing?

**Comment by testica** [comment]
@DrCod Do you have getter and setter of password attribute?

**Comment by DrCod** [comment]
@testica  Yes I do

**Comment by testica** [comment]
@DrCod your code seems to be right.
Did you check that post payload is empty ?

**Comment by DrCod** [comment]
@testica  I get a "Unprocessable Entity" message in my response body.

**Comment by DrCod** [comment]
I resolved the error!

Doing this resolved it for me.
@POST("/users/")
Call<JSONApiObject>register(@Query("user[email]") String email,@Query("user[password]") String password);

**Comment by faogustavo** [comment]
As this problem was solved, I'm closing the issue.
