### ISSUE TITLE
Inner object

### ISSUE THREAD

**Issue by starikovskii** [faogustavo/JSONApi#27]
**I have next architecture :** 
Comment ->User->ProfileCard->ProfileData

`public class Comment extends Resource {
     //some attributes
     @Expose
    @SerialName(Constants.Network.Models.Comments.USER)
    User user;

    @Expose
    @SerialName(Constants.Network.Models.Comments.SUBCOMMENTS)
    JSONList<Comment> subcomments;

    public Comment() {
    } 
    //getters and setters
}
public class User extends Resource {

    //some attributes
    @SerialName(Constants.Network.Models.User.PROFILE_CARD)
    ProfileCard card;
 
    public User() {
    } 
   //getters and setters
}
public class ProfileCard extends Resource implements ICardMarker {

     //some attributes
    @SerialName(Constants.Network.Models.ProfileCard.PROFILE_DATA)
    ProfileData data;

    public ProfileCard() {
    }  
   //getters and setters
}
public class ProfileData extends Resource {
    @SerialName(Constants.Network.Models.ProfileData.FULL_NAME)
    String fullName;

    public ProfileData() {
    }
`
**When i try to parse this response ProfileData attribute is null. can u help me?**
{"data":[{"id":"107","type":"comments","attributes":{"text":"Mmmm fantastic taste of music!","createdAt":"2016-07-05T17:32:58.947Z","updatedAt":"2016-07-05T17:32:58.947Z"},"relationships":{"user":{"data":{"id":"5","type":"users"}},"subcomments":{"data":[]}}}],"included":[{"id":"5","type":"users","relationships":{"profileCard":{"data":{"id":"11","type":"profileCards"}}}},{"id":"11","type":"profileCards","attributes":{"profileCardImageOriginal":"somelink","profileCardImageBig":"somelink","profileCardImageMedium":"somelink","profileCardImageSmall":"somelink"},"relationships":{"profileData":{"data":{"id":"5","type":"profileDatas"}}}},{"id":"5","type":"profileDatas","attributes":{"fullname":"Christoffer Wallin"}}],"links":{}}

**Comment by faogustavo** [comment]
Sorry for the late response, but did you find what caused the problem or solved your problem?
