### ISSUE TITLE
How to populate IDs

### ISSUE THREAD

**Issue by iaindownie** [faogustavo/JSONApi#7]
Hi - I'm new to your library (and JSON API). When I follow your docs with two simple objects (including a relationship between them using JSONList), I get 
"id": "null", or id is missing completely.
and can't work out how to set up the ID to replicate the first example on http://jsonapi.org/examples/

Can you provide any advice or documentation on handling ID's within relationships? Apologies if I've missed something really obvious...

Here's my output when serialising, which seems a bit oddly organised by the library by default:
{
	"included": [{
		"type": "observations",
		"id": "null",
		"attributes": {
			"comments": "A comment on Barnacle Geese",
			"count": "3",
			"speciesCode": "bargoo"
		}
	}, {
		"type": "observations",
		"id": "null",
		"attributes": {
			"count": "1",
			"speciesCode": "gragoo"
		}
	}],
	"data": {
		"type": "submissions",
		"attributes": {
			"locID": "L1863647",
			"projID": "MYPROJECT",
			"protocolID": "traveling"
		},
		"relationships": {
			"observations": {
				"data": [{
					"type": "observations"
				}, {
					"type": "observations"
				}]
			}
		}
	}
}

My two objects are:

`
@Type("observations")
public class Observations extends Resource {

    String speciesCode;
    String count;
    String comments;

    public Observations(String speciesCode, Observation anObs) {
        this.speciesCode = speciesCode;
        this.count = anObs.count.toString();
        this.comments = anObs.comments;
    }    
}
`

`
@Type("submissions")
public class Submissions extends Resource {

    String projID;

    @Excluded
    Submission submission;

    @Excluded
    BirdingLocation location;

    @Excluded
    SubmissionSession submissionSession;

    JSONList<Observations> observations;

    String locID;
    String protocolID;

    public String getProjID() {
        return projID;
    }

    public void setProjID(String projID) {
        this.projID = projID;
    }

    public void setSubmissionSession(SubmissionSession submissionSession) {
        this.submissionSession = submissionSession;
        this.submission = submissionSession.getSubmission();
        this.projID = "MYPROJECT";
        this.location = submission.getLocation();
        this.locID = location.locationID;
        this.protocolID = submission.protocolId;
        Map<String, Observation> allObs = submissionSession.getObservations();
        observations = new JSONList<>();
        ArrayList species = new ArrayList(allObs.keySet());
        for (int i = 0; i < species.size(); i++) {
            Observations anObs = new Observations((String) species.get(i), allObs.get(species.get(i)));
            observations.add(anObs);
        }
    }

    public JSONList<Observations> getObservations() {
        return observations;
    }

    public void setObservations(JSONList<Observations> observations) {
        this.observations = observations;
    }

    public String getLocID() {
        return locID;
    }

    public void setLocID(String locID) {
        this.locID = locID;
    }

    public String getProtocolID() {
        return protocolID;
    }

    public void setProtocolID(String protocolID) {
        this.protocolID = protocolID;
    }
    
}
`

**Comment by faogustavo** [comment]
I'll try this tomorrow and try to give you an answer as soon as possible.

**Comment by iaindownie** [comment]
Thanks @faogustavo - much appreciated.
